### ISSUE TITLE
Wiring of level shifter

### ISSUE THREAD

**Issue by visini** [MartinNuc/logic-data-controller#1]
Hi there!

I'm trying to implement this project for my desk, and have tried to decipher the picture you posted in https://github.com/davidknezic/desk/issues/3 - However, I get mixed results: Sometimes the desk reacts correctly to API requests and/or hand switch UP/DOWN signals, but most of the times, it does not behave as I intended it to.

My wiring is outlined below:

<img width="973" alt="Screenshot 2020-10-25 at 11 06 28" src="https://user-images.githubusercontent.com/10230606/97104183-270bb300-16b2-11eb-8c99-7d84d3767202.png">

(bottom picture is from: https://www.mikrocontroller.net/topic/373579 – the colours correspond to the diagram above)

My question is: Can you find any flaw in my wiring diagram? I would be willing to prepare a correct and final diagram for you to include in this project readme for others.

Many thanks in advance for your help, and for your work on this project! Looking forward to try any suggestions you have...

**Comment by MartinNuc** [comment]
I am sorry I don't really remember the connection 🙈

But from what I've observed - what caused issues to me was when the CPU usage was bit high - the driver couldn't catch up with the signal channel and it got into weird state.

Given the complex wiring (3.3V vs 5V) and also the issue above I actually suggest using Arduino for controlling the table.
